[package]
name = "mkv-demux"
version = "0.0.1"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
description = "A simple Matroska demuxer that can demux Matroska and WebM container files."
license = "Zlib OR MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hasenbanck/mkv-demux"
categories = ["multimedia"]
keywords = ["matroska", "qebm", "demuxer", "demux"]
edition = "2018"

[dependencies]
